{
    'name': "POS Customization",
    'version': '17.0.1.0',
    'category': 'Education',
    'sequence': 4,
    'summary': "Pos Customization Task",
    'author': 'Jaymin Patel',
    'website': '',
    'depends': [
        'sale',
        'purchase',
        'point_of_sale',
    ],
    'data': [
        # 'security/ir.model.access.csv',
        # 'views/sale_order_view.xml',
        # 'views/report.xml',
    ],
    'demo': [
    ],
    'assets': {
        # 'point_of_sale.assets': [
        #     'module_name/static/src/js/filename.js',
        #     'module_name/static/src/xml/filename.xml',
        # ],
        'point_of_sale._assets_pos': [
            # 'tic_tac/static/src/app/**/*',
            'tic_tac/static/src/app/screens/product_screen/control_buttons/custom_button/custom_button.js',
            'tic_tac/static/src/app/screens/product_screen/control_buttons/custom_button/custom_button.xml',
            'tic_tac/static/src/app/screens/product_screen/control_buttons/custom_button_popup/custom_button_popup.js',
            'tic_tac/static/src/app/screens/product_screen/control_buttons/custom_button_popup/custom_button_popup.xml',
            # 'custom_pos_screen/static/src/app/**/*',
            # 'tic_tac/static/src/app/custom_button/custom_button.js',
            # 'tic_tac/static/src/app/custom_button/custom_button.xml',
            # 'tic_tac/static/src/app/custom_button_popup/custom_button_popup.js',
            # 'tic_tac/static/src/app/custom_button_popup/custom_button_popup.xml',
            # 'tic_tac/static/src/js/custom_button_pos.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 75,
    'currency': 'EUR',
    'license': 'Other proprietary',
}
